#!/usr/bin/env bash
# Shared helpers for GCP scripts. Source from setup/deploy/seed:
#   # shellcheck source=./common.sh
#   source "$(cd "$(dirname "$0")" && pwd)/common.sh"

GCP_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$GCP_SCRIPT_DIR/../.." && pwd)"
GCP_CONFIG_FILE="${GCP_CONFIG_FILE:-$GCP_SCRIPT_DIR/.env.gcp}"

_gcp_escape() {
  printf '%s' "$1" | sed "s/'/'\\\\''/g"
}

_gcp_write_kv() {
  local key="$1"
  local value="$2"
  printf "%s='%s'\n" "$key" "$(_gcp_escape "$value")"
}

load_gcp_config_file() {
  if [[ -f "$GCP_CONFIG_FILE" ]]; then
    # shellcheck disable=SC1090
    set -a
    source "$GCP_CONFIG_FILE"
    set +a
    return 0
  fi
  return 1
}

save_gcp_config_file() {
  mkdir -p "$(dirname "$GCP_CONFIG_FILE")"
  {
    echo "# Local GCP deploy config for Josh 背单词."
    echo "# Generated by scripts/gcp/*.sh — do not commit."
    echo "# Re-run setup with --reconfigure to rewrite interactively."
    echo
    _gcp_write_kv GCP_PROJECT "${GCP_PROJECT}"
    _gcp_write_kv GCP_REGION "${GCP_REGION:-asia-east1}"
    _gcp_write_kv CLOUD_SQL_INSTANCE "${CLOUD_SQL_INSTANCE:-rtsw-pg}"
    _gcp_write_kv CLOUD_SQL_DB "${CLOUD_SQL_DB:-rtsw}"
    _gcp_write_kv CLOUD_SQL_USER "${CLOUD_SQL_USER:-rtsw}"
    _gcp_write_kv ARTIFACT_REPO "${ARTIFACT_REPO:-rtsw}"
    _gcp_write_kv CLOUD_RUN_SERVICE "${CLOUD_RUN_SERVICE:-rtsw}"
    _gcp_write_kv CLOUD_RUN_SEED_JOB "${CLOUD_RUN_SEED_JOB:-rtsw-seed}"
    _gcp_write_kv BOOTSTRAP_ADMIN_USER "${BOOTSTRAP_ADMIN_USER:-admin}"
    _gcp_write_kv BOOTSTRAP_ADMIN_PASSWORD "${BOOTSTRAP_ADMIN_PASSWORD}"
    if [[ -n "${DB_PASSWORD:-}" ]]; then
      _gcp_write_kv DB_PASSWORD "${DB_PASSWORD}"
    fi
    if [[ -n "${JWT_SECRET:-}" ]]; then
      _gcp_write_kv JWT_SECRET "${JWT_SECRET}"
    fi
  } >"$GCP_CONFIG_FILE"
  chmod 600 "$GCP_CONFIG_FILE"
  echo "Saved GCP config -> $GCP_CONFIG_FILE"
}

_prompt_value() {
  local var_name="$1"
  local label="$2"
  local default="${3:-}"
  local secret="${4:-0}"
  local current="${!var_name:-}"
  local input=""

  if [[ -n "$current" ]]; then
    return 0
  fi

  if [[ -n "$default" ]]; then
    if [[ "$secret" == "1" ]]; then
      read -r -s -p "$label [$default]: " input
      echo
    else
      read -r -p "$label [$default]: " input
    fi
    printf -v "$var_name" '%s' "${input:-$default}"
  else
    while true; do
      if [[ "$secret" == "1" ]]; then
        read -r -s -p "$label: " input
        echo
      else
        read -r -p "$label: " input
      fi
      if [[ -n "$input" ]]; then
        printf -v "$var_name" '%s' "$input"
        break
      fi
      echo "  (required)"
    done
  fi
}

_list_gcloud_projects() {
  if ! command -v gcloud >/dev/null 2>&1; then
    return 1
  fi
  gcloud projects list --format='value(projectId)' 2>/dev/null | head -30 || true
}

ensure_gcp_config() {
  local force="${1:-0}"
  local had_file=0

  if load_gcp_config_file; then
    had_file=1
  fi

  # Explicit env vars still win over the file when the caller exports them.
  :
  GCP_REGION="${GCP_REGION:-asia-east1}"
  CLOUD_SQL_INSTANCE="${CLOUD_SQL_INSTANCE:-rtsw-pg}"
  CLOUD_SQL_DB="${CLOUD_SQL_DB:-rtsw}"
  CLOUD_SQL_USER="${CLOUD_SQL_USER:-rtsw}"
  ARTIFACT_REPO="${ARTIFACT_REPO:-rtsw}"
  CLOUD_RUN_SERVICE="${CLOUD_RUN_SERVICE:-rtsw}"
  CLOUD_RUN_SEED_JOB="${CLOUD_RUN_SEED_JOB:-rtsw-seed}"
  BOOTSTRAP_ADMIN_USER="${BOOTSTRAP_ADMIN_USER:-admin}"

  local missing=0
  [[ -z "${GCP_PROJECT:-}" ]] && missing=1
  [[ -z "${BOOTSTRAP_ADMIN_PASSWORD:-}" ]] && missing=1

  if [[ "$force" != "1" && "$had_file" -eq 1 && "$missing" -eq 0 ]]; then
    echo "Using saved GCP config: $GCP_CONFIG_FILE"
    echo "  project:  $GCP_PROJECT"
    echo "  region:   $GCP_REGION"
    echo "  service:  $CLOUD_RUN_SERVICE"
    echo "  admin:    $BOOTSTRAP_ADMIN_USER"
    return 0
  fi

  if [[ ! -t 0 ]]; then
    echo "Missing GCP config and stdin is not a TTY." >&2
    echo "Create $GCP_CONFIG_FILE or export GCP_PROJECT and BOOTSTRAP_ADMIN_PASSWORD." >&2
    exit 1
  fi

  echo
  if [[ "$had_file" -eq 1 ]]; then
    echo "Saved GCP config is incomplete (or --reconfigure). Fill in the blanks."
  else
    echo "No local GCP config yet. Answer a few questions; they will be saved to:"
    echo "  $GCP_CONFIG_FILE"
  fi
  echo

  if [[ -z "${GCP_PROJECT:-}" ]]; then
    local projects current
    current="$(gcloud config get-value project 2>/dev/null || true)"
    projects="$(_list_gcloud_projects)"
    if [[ -n "$projects" ]]; then
      echo "Available GCP projects:"
      echo "$projects" | sed 's/^/  - /'
      echo
    fi
    _prompt_value GCP_PROJECT "GCP project ID" "$current"
  fi

  _prompt_value GCP_REGION "Region" "${GCP_REGION:-asia-east1}"
  _prompt_value CLOUD_RUN_SERVICE "Cloud Run service name" "${CLOUD_RUN_SERVICE:-rtsw}"
  _prompt_value CLOUD_SQL_INSTANCE "Cloud SQL instance id" "${CLOUD_SQL_INSTANCE:-rtsw-pg}"
  _prompt_value ARTIFACT_REPO "Artifact Registry repo" "${ARTIFACT_REPO:-rtsw}"
  _prompt_value BOOTSTRAP_ADMIN_USER "Bootstrap admin username" "${BOOTSTRAP_ADMIN_USER:-admin}"

  if [[ -z "${BOOTSTRAP_ADMIN_PASSWORD:-}" ]]; then
    _prompt_value BOOTSTRAP_ADMIN_PASSWORD "Bootstrap admin password" "" 1
    local confirm=""
    read -r -s -p "Confirm admin password: " confirm
    echo
    if [[ "$confirm" != "$BOOTSTRAP_ADMIN_PASSWORD" ]]; then
      echo "Passwords do not match." >&2
      exit 1
    fi
  fi

  if [[ -z "${DB_PASSWORD:-}" ]]; then
    DB_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)"
  fi
  if [[ -z "${JWT_SECRET:-}" ]]; then
    JWT_SECRET="$(openssl rand -hex 32)"
  fi

  save_gcp_config_file
}

need_gcloud() {
  if ! command -v gcloud >/dev/null 2>&1; then
    echo "gcloud CLI not found. Install Google Cloud SDK, then run: gcloud auth login" >&2
    exit 1
  fi
}

apply_gcp_defaults() {
  export GCP_PROJECT
  export GCP_REGION="${GCP_REGION:-asia-east1}"
  export CLOUD_SQL_INSTANCE="${CLOUD_SQL_INSTANCE:-rtsw-pg}"
  export CLOUD_SQL_DB="${CLOUD_SQL_DB:-rtsw}"
  export CLOUD_SQL_USER="${CLOUD_SQL_USER:-rtsw}"
  export ARTIFACT_REPO="${ARTIFACT_REPO:-rtsw}"
  export CLOUD_RUN_SERVICE="${CLOUD_RUN_SERVICE:-rtsw}"
  export CLOUD_RUN_SEED_JOB="${CLOUD_RUN_SEED_JOB:-rtsw-seed}"
  export BOOTSTRAP_ADMIN_USER="${BOOTSTRAP_ADMIN_USER:-admin}"
  export BOOTSTRAP_ADMIN_PASSWORD
  export DB_PASSWORD="${DB_PASSWORD:-}"
  export JWT_SECRET="${JWT_SECRET:-}"
}
