#!/usr/bin/env python3
"""Add explanation field to wordbook CSVs for words that benefit from it."""

import csv
import os
from pathlib import Path

DATASETS_DIR = Path(__file__).parent.parent / "datasets"

# Explanation dictionary: word -> explanation string
# Only include words where extra context helps learning.
# Skip: basic words, sentence fragments, past tenses, phrases too specific to context
EXPLANATIONS = {
    # === KET3 words ===
    "be interested in": "phrase. 对…感兴趣。后接名词或动名词(v-ing)",
    "career": "n. 职业；事业。指长期从事的工作方向，比 job 更正式",
    "extra": "adj./n. 额外的；附加的。pay extra 额外付费",
    "foreign language": "n. 外语。foreign adj. 外国的",
    "visitor": "n. 访客；游客。动词 visit → visitor",
    "download": "v./n. 下载。反义词 upload 上传",
    "match": "n./v. 比赛；匹配。football match 足球比赛",
    "without": "prep. 没有；不带。反义词 with",
    "contact": "v./n. 联系；联络。contact sb. 联系某人",
    "experience": "n./v. 经验；经历。可数(一次经历)或不可数(经验)",
    "improve": "v. 改善；提高。improvement n. 改进",
    "unfortunately": "adv. 不幸地；遗憾地。反义词 fortunately",
    "delay": "n./v. 延迟；推迟。without delay 立刻",
    "decide": "v. 决定。decide to do sth. 决定做某事",
    "arrive": "v. 到达。arrive at(小地点)/in(大地点)",
    "vocabulary": "n. 词汇；词汇量。不可数名词",
    "bracelet": "n. 手镯；手链",
    "earrings": "n. 耳环(常用复数)",
    "necklace": "n. 项链",
    "journalist": "n. 记者；新闻工作者",
    "possible": "adj. 可能的。反义词 impossible",
    "twice": "adv. 两次；两倍。twice a week 每周两次",
    "complete": "adj./v. 完整的；完成。completely adv. 完全地",
    "discount": "n. 折扣。at a discount 打折",
    "volleyball": "n. 排球",
    "popular": "adj. 受欢迎的；流行的。be popular with 受…欢迎",
    "crowded": "adj. 拥挤的。a crowded bus 拥挤的公共汽车",
    "believe": "v. 相信；认为。believe in 信仰",
    "actually": "adv. 实际上；事实上",
    "certainly": "adv. 当然；确实",
    "gate": "n. 大门；登机口",
    "fact": "n. 事实。in fact 事实上",
    "pity": "n. 遗憾；可惜。What a pity! 真可惜！",
    "suggest": "v. 建议。suggest doing sth. / suggest that...",
    "explain": "v. 解释；说明。explain sth. to sb.",
    "tent": "n. 帐篷",
    "interesting": "adj. 有趣的(修饰事物)。interested 感兴趣的(修饰人)",
    "borrow": "v. 借入。反义词 lend 借出",
    "textbook": "n. 教科书；课本",
    "attractive": "adj. 有吸引力的；迷人的。attract v. 吸引",
    "hope": "v./n. 希望。hope to do sth. / hope that...",
    "meal": "n. 一餐。three meals a day 一日三餐",
    "chef": "n. 厨师(尤指餐厅主厨)",
    "tour guide": "n. 导游",
    "instrument": "n. 乐器；工具。musical instrument 乐器",
    "partner": "n. 伙伴；搭档",
    "skiing": "n. 滑雪。go skiing 去滑雪",
    "book": "v./n. 预订；书。book a ticket 订票",
    "would like to": "phrase. 想要(礼貌表达)。= want to",
    "change": "v./n. 改变；零钱",
    "check": "v./n. 检查；核实。check in 登记入住",
    "penpal": "n. 笔友。也写作 pen pal",
    "adventure": "n. 冒险；奇遇。adventurous adj. 爱冒险的",
    "adult": "n./adj. 成人(的)。反义词 child",
    "website": "n. 网站",
    "detail": "n. 细节。in detail 详细地",
    "date": "n. 日期；约会。v. 约会",
    "be able to": "phrase. 能够(= can，但可用于更多时态)",
    "including": "prep. 包括。include v. 包含",
    "guided tour": "n. 有导游的旅行",
    "information": "n. 信息(不可数)。a piece of information 一条信息",
    "practice": "n./v. 练习；实践。practice doing sth.",
    "offer": "v./n. 提供；报价。offer sb. sth. / offer to do",
    "opinion": "n. 意见；看法。in my opinion 在我看来",
    "already": "adv. 已经(用于肯定句)",
    "club": "n. 俱乐部；社团",
    "race": "n./v. 比赛；赛跑",
    "exhibition": "n. 展览。art exhibition 艺术展",
    "activity": "n. 活动(可数)。outdoor activities 户外活动",
    "area": "n. 地区；区域；面积",
    "however": "adv./conj. 然而；不过(转折)",
    "cycling": "n. 骑自行车。go cycling 去骑车",
    "baseball": "n. 棒球",
    "hockey": "n. 曲棍球；冰球",
    "describe": "v. 描述。describe sth. to sb.",
    "engineer": "n. 工程师",
    "astronaut": "n. 宇航员",
    "brilliant": "adj. 极好的；才华横溢的",
    "helpful": "adj. 有帮助的。be helpful to sb.",
    "blog": "n./v. 博客；写博客",
    "remember": "v. 记住。remember to do(记得去做) / doing(记得做过)",
    "planet": "n. 行星。the planet Mars 火星",
    "advice": "n. 建议(不可数)。a piece of advice 一条建议",
    "discuss": "v. 讨论。discuss sth. with sb.(不加 about)",
    "return": "v./n. 返回；归还。return ticket 往返票",
    "cheap": "adj. 便宜的。反义词 expensive",
    "unusual": "adj. 不寻常的。反义词 usual 通常的",
    "serve": "v. 服务；上菜。service n. 服务",
    "project": "n. 项目；课题",
    "leather": "n./adj. 皮革(的)。a leather bag 皮包",
    "size": "n. 尺寸；大小。What size? 什么尺码？",
    "surfing": "n. 冲浪。go surfing 去冲浪",
    "upset": "adj. 不安的；难过的。be upset about sth.",
    "favorite": "adj./n. 最喜欢的(人/物)。= favourite(英式)",
    "healthy": "adj. 健康的。反义词 unhealthy",
    "perfect": "adj. 完美的。perfectly adv.",
    "beginner": "n. 初学者。begin → beginner",
    "receptionist": "n. 前台接待员",
    "immediately": "adv. 立刻；马上。= at once",
    "band": "n. 乐队；带子",
    "enter": "v. 进入；参加(比赛)。enter a competition 参赛",
    "tram": "n. 有轨电车",
    "photographer": "n. 摄影师。photo → photograph → photographer",
    "skateboard": "n./v. 滑板",
    "campsite": "n. 露营地。camp + site",
    "market": "n. 市场。supermarket 超市",
    "beach": "n. 海滩。on the beach 在海滩上",
    "course": "n. 课程；过程。of course 当然",
    "artist": "n. 艺术家。art → artist",
    "agree": "v. 同意。agree with sb. / agree to do sth.",
    "windsurfing": "n. 帆板运动",
    "instruction": "n. 指示；说明(常用复数 instructions)",
    "magazine": "n. 杂志",
    "length": "n. 长度。long → length",
    "jewelry": "n. 珠宝(总称，不可数)。a piece of jewelry 一件珠宝",
    "college": "n. 学院；大学",
    "reason": "n. 原因；理由。the reason for/why...",
    "filmmaking": "n. 电影制作",
    "pavement": "n. 人行道(英式)。美式用 sidewalk",

    # === KET3 continued ===
    "college": "n. 学院；大学",
    "reason": "n. 原因；理由。the reason for/why...",
    "filmmaking": "n. 电影制作",
    "pavement": "n. 人行道(英式)。美式用 sidewalk",
    "soon": "adv. 不久；很快。as soon as 一…就…",

    # === School 6 words ===
    "Canada": "n. 加拿大。Canadian adj./n. 加拿大的/人",
    "excited": "adj. 兴奋的(修饰人)。exciting 令人兴奋的(修饰事物)",
    "winter": "n. 冬天。in winter 在冬天",
    "Australia": "n. 澳大利亚。Australian adj./n.",
    "London": "n. 伦敦(英国首都)",
    "Washington D.C.": "n. 华盛顿特区(美国首都)",
    "Sydney": "n. 悉尼(澳大利亚城市)",
    "Toronto": "n. 多伦多(加拿大城市)",
    "tomorrow": "n./adv. 明天。反义词 yesterday",
    "trip": "n. 旅行(短途)。go on a trip 去旅行",
    "lake": "n. 湖。lake + 名：Lake Ontario",
    "ocean": "n. 海洋。the Pacific Ocean 太平洋",
    "country": "n. 国家；乡村。in the country 在乡下",
    "cousin": "n. 表/堂兄弟姐妹",
    "capital": "n./adj. 首都；大写的。capital letter 大写字母",
    "grocery store": "n. 杂货店。= grocery shop",
    "department store": "n. 百货商店",
    "turn left": "phrase. 左转。反义：turn right",
    "turn right": "phrase. 右转",
    "go straight": "phrase. 直走",
    "traffic lights": "n. 交通信号灯(常用复数)",
    "across from": "prep. 在…对面。= opposite",
    "apartment": "n. 公寓。= flat(英式)",
    "address": "n. 地址；v. 演讲；称呼",
    "weather": "n. 天气(不可数)。How's the weather? 天气怎么样？",
    "temperature": "n. 温度。take one's temperature 量体温",
    "degree": "n. 度；学位。30 degrees 30度",
    "forecast": "n./v. 预报。weather forecast 天气预报",
    "umbrella": "n. 雨伞",
    "raincoat": "n. 雨衣。rain + coat",
    "outside": "adv./prep./n. 外面。反义词 inside",
    "scarf": "n. 围巾。复数 scarves/scarfs",
    "newspaper": "n. 报纸。news + paper",
    "surprise": "n./v. 惊喜；使惊讶。surprised adj. 感到惊讶的",
    "loudly": "adv. 大声地。loud adj. → loudly adv.",
    "diary": "n. 日记。keep a diary 写日记",
    "subject": "n. 科目；主题；主语",
    "geography": "n. 地理",
    "biology": "n. 生物学",
    "physics": "n. 物理学",
    "schedule": "n./v. 时间表；安排",
    "lifestyle": "n. 生活方式",
    "healthy": "adj. 健康的。keep healthy 保持健康",
    "exercise": "n./v. 锻炼；练习。do/take exercise 做运动",
    "energy": "n. 精力；能量",
    "breakfast": "n. 早餐。have breakfast 吃早餐",
    "brush teeth": "phrase. 刷牙。brush one's teeth",
    "habit": "n. 习惯。good/bad habits 好/坏习惯",
    "hobby": "n. 爱好。复数 hobbies",
    "collect": "v. 收集。collection n. 收藏",
    "model": "n. 模型；模特。model plane 模型飞机",
    "stamp": "n. 邮票；v. 盖章",
    "insect": "n. 昆虫",
    "roller coaster": "n. 过山车",
    "museum": "n. 博物馆",
    "amusement park": "n. 游乐园",
    "aquarium": "n. 水族馆",
    "souvenir": "n. 纪念品。buy souvenirs 买纪念品",
    "camera": "n. 照相机",
    "kangaroo": "n. 袋鼠(澳大利亚代表动物)",
    "koala": "n. 考拉；树袋熊",
    "bamboo": "n. 竹子(不可数)",
    "panda": "n. 熊猫。giant panda 大熊猫",
    "ocean": "n. 海洋。the Pacific Ocean 太平洋",
    "island": "n. 岛屿。注意 s 不发音",
    "desert": "n. 沙漠。注意区分 dessert(甜点)",
    "forest": "n. 森林。rainforest 雨林",
    "mountain": "n. 山。climb a mountain 爬山",
    "valley": "n. 山谷",
    "waterfall": "n. 瀑布。water + fall",
    "culture": "n. 文化。cultural adj. 文化的",
    "tradition": "n. 传统。traditional adj. 传统的",
    "festival": "n. 节日。Spring Festival 春节",
    "celebrate": "v. 庆祝。celebration n. 庆祝活动",
    "vacation": "n. 假期。on vacation 在度假",
    "sunglasses": "n. 太阳镜(常用复数)",
    "suitcase": "n. 手提箱；行李箱",
    "passenger": "n. 乘客",
    "flight": "n. 航班；飞行。flight number 航班号",
    "passport": "n. 护照",
    "arrival": "n. 到达。arrive v. → arrival n.",
    "departure": "n. 出发；离开。depart v. → departure n.",
    "destination": "n. 目的地",
    "volunteer": "n./v. 志愿者；自愿做",
    "environment": "n. 环境。protect the environment 保护环境",
    "recycle": "v. 回收利用。recyclable adj. 可回收的",
    "plant": "n./v. 植物；种植。plant trees 植树",
    "protect": "v. 保护。protect...from... 保护…免受…",
    "village": "n. 村庄。反义词 city",
    "ancient": "adj. 古代的；古老的。ancient China 古代中国",
    "palace": "n. 宫殿。the Summer Palace 颐和园",
    "tower": "n. 塔。the Eiffel Tower 埃菲尔铁塔",
    "century": "n. 世纪。the 21st century 21世纪",
    "emperor": "n. 皇帝。empress n. 女皇",
    "hometown": "n. 家乡；故乡",
    "invite": "v. 邀请。invite sb. to do sth.",
    "excited": "adj. 兴奋的(修饰人)。be excited about 对…兴奋",
    "invitation": "n. 邀请。invite v. → invitation n.",
    "prepare": "v. 准备。prepare for 为…准备",
    "nervous": "adj. 紧张的。be nervous about 对…紧张",
    "platform": "n. 站台；平台",
    "passenger": "n. 乘客；旅客",
    "luggage": "n. 行李(不可数)。a piece of luggage 一件行李",
    "backpack": "n. 双肩背包",
    "tent": "n. 帐篷。put up a tent 搭帐篷",
    "campfire": "n. 营火；篝火。camp + fire",
    "sleeping bag": "n. 睡袋",
    "flashlight": "n. 手电筒。= torch(英式)",
    "sunset": "n. 日落。反义词 sunrise 日出",
    "sunrise": "n. 日出。sun + rise",
    "scenery": "n. 风景(不可数)。beautiful scenery 美丽的风景",
    "view": "n. 景色；观点。a sea view 海景",
    "breathe": "v. 呼吸。breath n. 呼吸",
    "fresh": "adj. 新鲜的；清新的。fresh air 新鲜空气",
    "picnic": "n. 野餐。have a picnic 野餐",
    "barbecue": "n./v. 烧烤。= BBQ",
    "memory": "n. 记忆；回忆。memories 复数",
    "unforgettable": "adj. 难忘的。un + forget + able",
    "grass": "n. 草(不可数)。on the grass 在草地上",

    # School 6 — Unit 1 supplements
    "worried": "adj. 担心的。be worried about 担心…",
    "autumn": "n. 秋天(英式)。美式用 fall",
    "rainy": "adj. 多雨的。rain → rainy",
    "windy": "adj. 多风的。wind → windy",
    "cloudy": "adj. 多云的。cloud → cloudy",
    "polite": "adj. 有礼貌的。反义词 impolite/rude",

    # School 6 — Unit 2 supplements
    "library": "n. 图书馆。librarian n. 图书管理员",
    "cinema": "n. 电影院(英式)。美式 movie theater",
    "theatre": "n. 剧院(英式拼写)。美式 theater",
    "crossroad": "n. 十字路口。= crossroads",
    "airport": "n. 机场。air + port",
    "stadium": "n. 体育场；体育馆",
    "boring": "adj. 无聊的(修饰事物)。bored 感到无聊的(修饰人)",
    "fantastic": "adj. 极好的；了不起的",
    "wonderful": "adj. 精彩的；极好的。= great, fantastic",
    "hardworking": "adj. 勤奋的。= hard-working",
    "handsome": "adj. 英俊的(多形容男性)",
    "slim": "adj. 苗条的；纤细的",

    # School 6 — Unit 3 supplements
    "wake up": "phrase. 醒来。wake-woke-woken",
    "housework": "n. 家务(不可数)。do housework 做家务",
    "subway": "n. 地铁(美式)。英式用 underground/tube",
    "sandwich": "n. 三明治。复数 sandwiches",
    "sausage": "n. 香肠",
    "French fries": "n. 炸薯条(美式)。英式用 chips",
    "dumpling": "n. 饺子",
    "headache": "n. 头痛。have a headache 头疼",
    "stomachache": "n. 胃痛/肚子痛",
    "toothache": "n. 牙痛。tooth → toothache",
    "square": "n. 广场；正方形。adj. 方形的",

    # School 6 — Unit 4 supplements
    "always": "adv. 总是(频率最高)。频率副词序：always>usually>often>sometimes>never",
    "sometimes": "adv. 有时候",
    "never": "adv. 从不(频率为零)",
    "bookstore": "n. 书店。= bookshop(英式)",
    "post office": "n. 邮局",

    # School 6 — Unit 5 supplements
    "Christmas": "n. 圣诞节(12月25日)。Merry Christmas! 圣诞快乐！",
    "Mid-Autumn Festival": "n. 中秋节。吃月饼 eat mooncakes",
    "butterfly": "n. 蝴蝶。复数 butterflies",
    "penguin": "n. 企鹅",
    "reptile": "n. 爬行动物。如蛇、蜥蜴、鳄鱼",
    "mammal": "n. 哺乳动物。如猫、狗、鲸鱼",
    "dangerous": "adj. 危险的。danger n. 危险",
    "curly": "adj. 卷曲的。curly hair 卷发",
    "straight": "adj. 直的；adv. 直接地。straight hair 直发",

    # School 6 — Unit 6 supplements
    "the USA": "n. 美国。= the United States of America",
    "the UK": "n. 英国。= the United Kingdom",
    "Beijing Opera": "n. 京剧。传统中国戏曲艺术",
    "vegetable": "n. 蔬菜。常用复数 vegetables",
    "seafood": "n. 海鲜(不可数)",
    "spicy food": "n. 辣味食物。spicy adj. 辛辣的",
    "southwest": "n./adj. 西南(方向)。south + west",
    "the Terracotta Army": "n. 兵马俑(西安)",
    "the Yangtze River": "n. 长江(中国最长河流)",
    "the Mogao Caves": "n. 莫高窟(敦煌)",
    "the Stone Forest": "n. 石林(云南)",
    "the Potala Palace": "n. 布达拉宫(西藏拉萨)",
    "West Lake": "n. 西湖(杭州)",
    "visit": "v. 参观；拜访。visitor n. 访客",
    "knife": "n. 小刀；刀。复数 knives",
}


def process_file(filepath: Path):
    rows = []
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        for row in reader:
            if not row or not row[0].strip():
                continue
            word = row[0].strip()
            # Ensure row has 6 columns
            while len(row) < 6:
                row.append('')
            # Add explanation if available and not already set
            if word in EXPLANATIONS and not row[5].strip():
                row[5] = EXPLANATIONS[word]
            rows.append(row)

    with open(filepath, 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f)
        for row in rows:
            writer.writerow(row)

    filled = sum(1 for r in rows if r[5].strip())
    return len(rows), filled


def main():
    csv_files = sorted(DATASETS_DIR.glob('*.csv'))
    total_words = 0
    total_filled = 0
    for f in csv_files:
        count, filled = process_file(f)
        total_words += count
        total_filled += filled
        print(f'  {f.name}: {count} words, {filled} with explanation')
    print(f'\nTotal: {total_words} words, {total_filled} with explanation ({total_filled*100//total_words}%)')


if __name__ == '__main__':
    main()
